// Callisto - callisto-task-youtube <https://github.com/msikma/callisto>
// © MIT license

const categories = {
  ALL_CATEGORIES: '0_0',
  ANIME: '1_0',
  ANIME_MUSIC_VIDEO: '1_1',
  ANIME_ENGLISH_TRANSLATED: '1_2',
  ANIME_NON_ENGLISH_TRANSLATED: '1_3',
  ANIME_RAW: '1_4',
  AUDIO: '2_0',
  AUDIO_LOSSLESS: '2_1',
  AUDIO_LOSSY: '2_2',
  LITERATURE: '3_0',
  LITERATURE_ENGLISH_TRANSLATED: '3_1',
  LITERATURE_NON_ENGLISH_TRANSLATED: '3_2',
  LITERATURE_RAW: '3_3',
  LIVE_ACTION: '4_0',
  LIVE_ACTION_ENGLISH_TRANSLATED: '4_1',
  LIVE_ACTION_IDOL_PROMOTIONAL_VIDEO: '4_2',
  LIVE_ACTION_NON_ENGLISH_TRANSLATED: '4_3',
  LIVE_ACTION_RAW: '4_4',
  PICTURES: '5_0',
  PICTURES_GRAPHICS: '5_1',
  PICTURES_PHOTOS: '5_2',
  SOFTWARE: '6_0',
  SOFTWARE_APPLICATIONS: '6_1',
  SOFTWARE_GAMES: '6_2'
}

module.exports = categories
